"""Add game_requirement_sessions table

Revision ID: 9168cc7b9b29
Revises: 424a42812448
Create Date: 2025-04-07 09:27:54.368898

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9168cc7b9b29'
down_revision = '424a42812448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_requirement_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_game_requirement_sessions_app_id')
        batch_op.drop_index('ix_game_requirement_sessions_tenant_id')
        batch_op.drop_index('ix_game_requirement_sessions_user_id')

    op.drop_table('game_requirement_sessions')
    with op.batch_alter_table('tool_published_apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', models.types.StringUUID(), nullable=False))
        batch_op.add_column(sa.Column('conversation_id', models.types.StringUUID(), nullable=True))
        batch_op.add_column(sa.Column('file_key', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('original_url', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=False))

    with op.batch_alter_table('workflow_app_logs', schema=None) as batch_op:
        batch_op.drop_index('workflow_app_log_app_idx')
        batch_op.create_index('workflow_app_log_app_idx', ['tenant_id', 'app_id', 'created_at'], unique=False)
        batch_op.create_index('workflow_app_log_workflow_run_idx', ['workflow_run_id'], unique=False)

    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index('workflow_conversation_variables_app_id_idx')
        batch_op.drop_index('workflow_conversation_variables_created_at_idx')
        batch_op.create_index('workflow__conversation_variables_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('workflow__conversation_variables_created_at_idx', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index('workflow__conversation_variables_created_at_idx')
        batch_op.drop_index('workflow__conversation_variables_app_id_idx')
        batch_op.create_index('workflow_conversation_variables_created_at_idx', ['created_at'], unique=False)
        batch_op.create_index('workflow_conversation_variables_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('workflow_app_logs', schema=None) as batch_op:
        batch_op.drop_index('workflow_app_log_workflow_run_idx')
        batch_op.drop_index('workflow_app_log_app_idx')
        batch_op.create_index('workflow_app_log_app_idx', ['tenant_id', 'app_id'], unique=False)

    with op.batch_alter_table('tool_published_apps', schema=None) as batch_op:
        batch_op.drop_column('size')
        batch_op.drop_column('name')
        batch_op.drop_column('original_url')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('file_key')
        batch_op.drop_column('conversation_id')
        batch_op.drop_column('tenant_id')

    op.create_table('game_requirement_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=36), server_default=sa.text("'requirements'::character varying"), autoincrement=False, nullable=False),
    sa.Column('requirement_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('history_messages', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='game_requirement_session_pkey')
    )
    with op.batch_alter_table('game_requirement_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_game_requirement_sessions_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_game_requirement_sessions_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('ix_game_requirement_sessions_app_id', ['app_id'], unique=False)

    # ### end Alembic commands ###
